version: '3.8'
services:
  postgres-file-service-db:
    image: postgres
    container_name: file-service-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=file-service
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5555:5432"
    volumes:
      - postgres-file-service-db-data:/var/lib/postgresql/data

  postgres-note-app-db:
    image: postgres
    container_name: note-app-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=note-app
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5666:5432"
    volumes:
      - postgres-note-app-db-data:/var/lib/postgresql/data

volumes:
  postgres-file-service-db-data:
    driver: local
  postgres-note-app-db-data:
    driver: local