version: '3.8'
services:
  postgres-db:
    image: postgres
    container_name: file-service-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=file-service
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5555:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local