spring:
  application:
    name: note-app

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5666/note-app}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /v1/note-app

file-service:
  url: ${FILE_SERVICE_URL:http://localhost:8085/v1/file-service}